In [4]:
import numpy as np
arr = np.arange(100,200,10).reshape(5,2)
arr

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [16]:
#Print 3rd column of all rows
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
sampleArray[...,2]

array([33, 66, 99])

In [19]:
#Following is the given numpy array return array of odd rows and even columns
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
sampleArray[::2,1::2]

array([[ 6, 12],
       [30, 36],
       [54, 60]])

In [25]:
#Add the following two NumPy arrays and Modify a result array by calculating the square root of each element
import numpy as np
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
resultarr = arrayOne+arrayTwo
print(np.square(resultarr))

[[ 400 1521 1089]
 [ 625  625  784]]


In [33]:
arr = np.arange(10,34,1).reshape(8,3)
arr1 = np.split(arr,4)
arr1

[array([[10, 11, 12],
        [13, 14, 15]]), array([[16, 17, 18],
        [19, 20, 21]]), array([[22, 23, 24],
        [25, 26, 27]]), array([[28, 29, 30],
        [31, 32, 33]])]

In [38]:
import numpy
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

In [41]:
import numpy as np
arr = [0,1,2,3,4,5,6,7,8]
arr = np.array(arr)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
arr = [[1,2],[3,4],[5,6]]
arr = np.array(arr)
np.mean(arr,axis=0)

array([3., 4.])

In [70]:
arr = [1.3, 2.1, 3.2, 4.4, 5.5, 6.6, 7.3, 8.8, 9.9]
arr = np.array(arr)
np.rint(arr)

array([ 1.,  2.,  3.,  4.,  6.,  7.,  7.,  9., 10.])

In [77]:
arr = np.array([[1,2],[3,4],[5,6],[7,8]])
print(arr.size)
print(arr.itemsize)
print(arr.size*arr.itemsize)

8
4
32


In [79]:
ida = np.identity(3)
ida[::-1]

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [84]:
z = np.identity(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [90]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [93]:
Z = np.zeros((3,3))
Z += np.arange(3)
Z

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [98]:
z = np.linspace(0,1,11,endpoint=False)[1:]
z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [111]:
A = np.array([1,2])
B = np.array([1,2])
A[A.argmax()]=0
A.sort()
A

array([0, 1])

In [112]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [113]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [114]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
